import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "MailMaven | Your One Stop Email Marketing Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
